### ISSUE TITLE
Not getting rid the stupid weekly digest

### ISSUE THREAD

**Issue by Egg-Roll** [Diabetaco/AutoPilot#1]
Hey thanks for this, it works on getting rid of the annoying course evaluations but it's not getting rid of the weekly digest. If you figure out how to fix it that would be great lol

**Comment by Diabetaco** [comment]
> Hey thanks for this, it works on getting rid of the annoying course evaluations but it's not getting rid of the weekly digest. If you figure out how to fix it that would be great lol

I found the issue being where I was looking for a string that only looked at my enrollment value. I think it should be fixed now that I'm looking for the CECS weekly digest text and then looking at its parent node and removing it. You can update your local version of this package and it should be working correctly.
